language: php
php:
  - 7.1

sudo: required
dist: trusty
addons:
  chrome: stable

  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

install:
   - cp .env.travis .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - mysql -e 'create database soen341;'
   - mysql -u root soen341 < database/database.sql
   - mysql -u root soen341 < database/notification.sql
   - php artisan key:generate
   - php artisan config:clear
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3 # give xvfb some time to start
   - php artisan serve --port=5432 &
   - sleep 3
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5432/&
   - sleep 3

script:
   - php artisan dusk