language: php
php:
  - 7.1

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=base64:SeofiwFYw/63WrsyKyqkGj2+cR5SmNLpYKN4LdOAsIQ=
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - QUEUE_DRIVER=sync

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
   - composer install

script: vendor/bin/phpunit