sudo: required
dist: trusty
language: php
php:
  - 7.1

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=false
    - APP_URL=http://96.21.224.83:8000
    - APP_KEY=base64:SeofiwFYw/63WrsyKyqkGj2+cR5SmNLpYKN4LdOAsIQ=
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - QUEUE_DRIVER=sync

addons:
  chrome: stable
  apt:
      sources:
        - mysql-5.7-trusty
      packages:
        - mysql-server
        - mysql-client

install:
   - cp .env.testing .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - mysql -e 'create database soen341;'
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://96.21.224.83 &
   - php artisan serve &

script:
   - php artisan dusk
   - vendor/bin/phpunit