language: php
php:
  - 7.1

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=base64:SeofiwFYw/63WrsyKyqkGj2+cR5SmNLpYKN4LdOAsIQ=
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - QUEUE_DRIVER=sync

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  sauce_connect:
      username: "abdullahzen"
      access_key: "c766de42-6bdf-4f5c-ac38-4fb057a46edc"

before_script:
   - composer self-update
   - composer install --no-interaction
   - cp .env.travis .env
   - php artisan key:generate
   - php artisan config:clear
   - mysql -e 'create database soen341;'
   - php artisan migrate
   - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
   - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
   - sudo apt-get update
   - sudo apt-get install google-chrome-stable

script: vendor/bin/phpunit