language: php
php:
  - 7.1

sudo: required
dist: trusty
addons:
  chrome: stable
  hosts:
      - localhost:8080

  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

install:
   - cp .env.travis .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - mysql -e 'create database soen341;'
   - php artisan migrate --seed
   - sudo mysql -h 127.0.0.1 -u root soen341 < database/database.sql
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3 # give xvfb some time to start
   - php artisan key:generate
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve --port=8080 --env=dusk.local &

script:
   - php artisan dusk