language: php
php:
  - 7.1

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=base64:SeofiwFYw/63WrsyKyqkGj2+cR5SmNLpYKN4LdOAsIQ=
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - QUEUE_DRIVER=sync

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  sauce_connect:
      username: "abdullahzen"
      access_key: "c766de42-6bdf-4f5c-ac38-4fb057a46edc"

before_script:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 # give xvfb some time to start
   - rackup  # start a Web server
   - sleep 3 # give Web server some time to bind to sockets, etc
   - composer self-update
   - composer install --no-interaction
   - cp .env.travis .env
   - php artisan key:generate
   - php artisan config:clear
   - mysql -e 'create database soen341;'
   - php artisan migrate

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script: vendor/bin/phpunit