language: php
sudo: required
dist: trusty

php:
  - 7.1

addons:
  chrome: stable

  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - cp .env.travis .env
  - mysql -e 'create database soen341;'
  - composer self-update
  - composer install --no-interaction
  - sudo mysql -h 127.0.0.1 -u root soen341 < database/database.sql
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000 &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk