language: php
php:
  - 7.1

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=base64:SeofiwFYw/63WrsyKyqkGj2+cR5SmNLpYKN4LdOAsIQ=
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - QUEUE_DRIVER=sync

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
   - composer self-update
   - composer install --no-interaction
   - cp .env.travis .env
   - php artisan key:generate
   - php artisan config:clear
   - php artisan vendor:publish
   - mysql -e 'create database soen341;'
   - php artisan migrate


script: vendor/bin/phpunit