# PHP CircleCI 2.0 configuration file for Laravel 5.5 and Laravel Dusk by Wes Mahler
# Author wesmahler.com
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-browsers
    working_directory: ~/laravel
    steps:
      - checkout


      # Leave this for future use if php-zip is ever required
      # If you remove the flag 'composer install --ignore-platform-reqs`
      # composer will require php-zip to be installed. It appers that
      # this isn't currently needed, so we are removing this from CircleCI
      # to save 30 seconds of build time. The php-zip package isn't currently
      # used by anything. If it ever does need to be used again, this can be
      # uncommented.

      #- run:
      #   name: Install PHP libzip-dev
      #   command: sudo apt-get install -y libzip-dev

      #- run:
      #   name: Install zip package for PHP
      #   command: sudo docker-php-ext-install zip

      - run:
         name: Setup Laravel testing environment variables for CircleCI test
         command: cp .env.circle .env

      - run:
         name: Update composer to latest version
         command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: sudo composer install -n --prefer-dist --ignore-platform-reqs --no-interaction
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
         name: Create sql Database
         command: mysql -e 'create database soen341;'

      - run:
          name: Create sql Database
          command: mysql -u root soen341 < database/database.sql

      - run:
          name: Create sql Database
          command: mysql -u root soen341 < database/notification.sql

      - run:
         name: Start Chrome Driver
         command: ./vendor/laravel/dusk/bin/chromedriver-linux
         background: true

      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true

      - run:
         name: Test 2 - Run Laravel Desk for Browser Testing
         command: php artisan dusk